### ISSUE TITLE
help with my legend

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/decsens#12]
@MoralesCastilla Could you make the legend on basicsimsandpep.pdf (coded in decsensSims.R) look better? Maybe it should just be outside the plot or something? I tried playing around but cannot make it look good, could you try? Thank you!

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver I have made a couple tweaks to the code to plot the legend as I showed in the .ai file. Let me know if you'd like any additional changes.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla Thanks for the great suggestion to add linear/non-linear to the main figure. I worked on adding it (see decsens.R and analyses/figures/basicsimsandpep.pdf). Can you check it and make any more tweaks to improve placement? Also, can you move the blue text for '1950-1960' down a touch? Thank you!
