### ISSUE TITLE
adjust chilling and forcing figures (F3 currently)

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/decsens#16]
@AileneKane Can you help adjust the chilling/forcing figure following Andrew's requests:

* When making the graphs, use bty="l", mgp=c(1.5, 0.25, 0), tck=-.01 so that they are more readable. (Please CHECK the mpg looks okay, I changed it as I thought the one Andrew suggested was too tight.)
* Flip the legend on the top graph so it matches Fig S2.
* The orange dots are higher on the graph; they should be higher on the legend. 
* bottom graphy: y-axis should not go below 0 or above 1.
* Change Fstar in legend to 'thermal sum required for leafout' 

Note that Andrew said "Also not clear what the axis on the right is doing. Better to just use another graph than to overload this one plot." I think it works personally so would leave it.

**Comment by AileneKane** [comment]
@lizzieinvancouver I have made the modifications above. Let me know if you'd like me to make this a 3 paneled figure, separating chilling and forcing as Andrew suggested

**Comment by AileneKane** [comment]
you could also try making the tables footnote sized

**Comment by lizzieinvancouver** [comment]
@AileneKane Up to you -- if you think 3 panels would be better we could switch, but I sort of think it works (because I sort of think only people interested in this mechanism will look at this figure). Thank you for doing this!

**Comment by AileneKane** [comment]
@lizzieinvancouver I think it's fine as is!

**Comment by AileneKane** [comment]
@lizzieinvancouver shall I close?

**Comment by lizzieinvancouver** [comment]
@AileneKane Yes! Thank you again for the work on this!
