### ISSUE TITLE
real data -- SWA sensitivities

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/decsens#2]
Use PEP725 data and try log-log relationship. See also #1

**Comment by cchambe12** [comment]
### Alright, now we have to convert to Kelvin again...
```
swapre$tempk <- swapre$climate + 273.15
swapost$tempk <- swapost$climate + 273.15

estprecc <- lm(yvar~tempk, data=swapre)
estpostcc <- lm(yvar~tempk, data=swapost)

diffbefore.after <- coef(estprecc)[2]-coef(estpostcc)[2]
```
diffbefore.after = -1.917594

```
estprecc.log <- lm(log(yvar)~log(tempk), data=swapre)
estpostcc.log <- lm(log(yvar)~log(tempk), data=swapost)

logdiffbefore.after <- coef(estprecc.log)[2]-coef(estpostcc.log)[2]
```

and logdiffbefore.after = -4.327136, exponentiated it's 0.01320532 so tiny increase in sensitivity!

**Comment by cchambe12** [comment]
@cchambe12 find credible intervals next

**Comment by lizzieinvancouver** [comment]
@cchambe12 Super cool! Thank you for doing this. Once you're writing out data, can you write out the estimates in a csv or such? I realized people get confused by graphing the diff so I have taken to graphing the raw sensitivities....

**Comment by cchambe12** [comment]
For sure! I've written out a .csv file here. I will make a README now. Let me know if you need anything else with this or if you want me to do anything different with the file. 

decsens/analyses/pep_analyses/output/swaestimates_withlog.csv

**Comment by cchambe12** [comment]
Still working on this... takes a veryyy long time and the results keep looking wonky. I need to find an appropriate window.

**Comment by cchambe12** [comment]
Example output from sliding window... not sure why the climate is so messed up. 

swapost
      X yvar     climate
1     1   93 -0.05881799
2     2   95 -0.05367270
3     3   96 -0.05813004
4     4   98 -0.05065594
5     5   99 -0.05748935
6     6  101 -0.05261041
7     7  101 -0.05951015
8     8  103 -0.05635570
9     9  104 -0.05929577
10   10  104 -0.06361004

**Comment by cchambe12** [comment]
We've done the best we can with this. We've decided to close this issue.
