### ISSUE TITLE
lit review of sensitivity studies

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/decsens#3]
[Here's a list to review](https://github.com/lizzieinvancouver/decsens/wiki/Lit-review-of-papers-using-temperature-sensitivity). Please put notes on any studies either in the wiki or in a new file in refs/litreview. Please add citations to the bib file of any papers that seem to have the issue we identify.

**Comment by lizzieinvancouver** [comment]
Dan is taking the lead on this!

**Comment by dbuona** [comment]
@lizzieinvancouver I will get going on this this week. I was also thinking (especially to find papers outside of phenology) we might consider using doing a search with the term "reaction norm" instead of sensitivity to potentially tap in to a different literature. I'll see how the list above pans out first..

**Comment by lizzieinvancouver** [comment]
@dbuona That sounds great! I think we (I) could use help thinking more expansively here....

**Comment by lizzieinvancouver** [comment]
@dbuona Can you let me know the name of the Zhu2019 article in the lit review file? I will try to track it down.

**Comment by dbuona** [comment]
Recent Warming Has Resulted in Smaller Gains in Net Carbon Uptake in Northern High Latitudes

**Comment by lizzieinvancouver** [comment]
See also #4 for discussion of Zhu2019 and Piao2017 which probably belonged here... @dbuona, please let me know if you think I interpreted those incorrectly and, if so, post here! Thanks.

(If not, we could close this issue I think.)

**Comment by lizzieinvancouver** [comment]
@dbuona See comment above sometime soon please!

**Comment by dbuona** [comment]
I agree that these two papers may have our issue.
In Piao 17 they say: "The interannual sensitivity of SZC (γSZC) to ST variation was computed as the slope of the regression of ST in a multiple linear regression of SZC against temperature, precipitation and cloud cover during the period from March to June. We apply the same approach to calculate interannual sensitivity of SCC (γSCC) to ST variation. " 
Note here ST is "spring temperature.
I will close the issue
