### ISSUE TITLE
Help with simulated data where sensitivities do decline

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/decsens#6]
See analyses/decsensSimsMo.R ...
Here's what I need help on:
1. I try to build winter to spring daily temp across i levels of warming with this command: 
`       daily_temp <- sapply(yearly_expected_temp, function(x) c(rnorm(daysperseason, 0 + i, sigma),
           rnorm(daysperinterseason, 2 + i , sigma), rnorm(daysperinterseason, 4 + i, sigma),
           rnorm(daysperseason, 6 + i, sigma)))`
But does this do what I think? Am I applying i correctly?
1. Look more at the intermediate output (climate data and when cstar and fstar are met) to make sure it makes sense. The tricky thing here is picking reasonable temps for real data (we used to match to the PEP data which has mean spring temps of 6 or such) but also having higher warming lead to declining sensitivities -- given that we assume chill does not accumulate below 0. Right now I am not sure how realistic this is ... so could use a lot of help evaluating this! Would be helpful to have some insight on this and maybe a few different base temperature versions ....
1. Figure out when sensitivities actually decline (i.e., can we flag when fstar does go up?) ... I imagine this has to do with how big the change in fstar is given declining cstar (that should determine when we see it), but given the linear approach I wonder is changing cstar and fstar may actually offset and make detection hard until large shifts or such?  ... Anyway, this would be a great thing if we could do it, as it would allow us to add something to the paper like, "we show true temperature sensitivities would need to decline XX% before being notable given a dataset of XX size." And could serve as an example of how simulating from a generative model can help.

**Comment by lizzieinvancouver** [comment]
Ailene will take a stab at this, Nacho said he can also help but, `pobably not before the last week of January'

**Comment by lizzieinvancouver** [comment]
@AileneKane Add figure or such showing sensitivities, % years chill not met and average Fstar across warming levels .... by Feb 5.

**Comment by AileneKane** [comment]
@lizzieinvancouver I did a[ rough cut at this](https://github.com/lizzieinvancouver/decsens/blob/master/analyses/figures/shiftingcuessims_3panels.pdf), but I'd love ideas for who to improve...do we want to make this all on one panel somehow? or at least combine the chilling and GDD to a single panel (could have 2 y axes)

**Comment by lizzieinvancouver** [comment]
@AileneKane Nice! I think it would be good to combine GDD and chilling % years. Is the GDD total just the total across the winter+spring? It seems we may only need GDD required (and it should never be below 200, right?).

**Comment by AileneKane** [comment]
@lizzieinvancouver Yes- the total is across the winter and spring season. And GDD requred is never below 200. I will combine GDD required and chilling on a single panel. Thanks!

**Comment by AileneKane** [comment]
@lizzieinvancouver I have added the new 2-panel figure [here](https://github.com/lizzieinvancouver/decsens/blob/master/analyses/figures/shiftingcuessims_2panels.pdf). Let me know if you want me to do anything else!

**Comment by lizzieinvancouver** [comment]
@AileneKane Can you provide a two panel figure showing a SINGLE regression (for one site I think: so doy ~ temperature, with each dot representing a year) from an early year where forcing dominates and a late year where chilling is not met?

**Comment by lizzieinvancouver** [comment]
So I guess a single regression per panel would be more accurate.

**Comment by AileneKane** [comment]
@lizzieinvancouver I'm not quite sure what temperature you mean- just the spring (forcing) temperature? Do you want just the regression line or the points of simulated data as well?

**Comment by lizzieinvancouver** [comment]
@AileneKane I am looking for a plot of the data that underlies EACH regression line. So in the code I think that's leafout_date versus yearly_temp.

**Comment by AileneKane** [comment]
Ok! I started by making 7 paneled figures- one fore every warming level. we can pare down to just 2- let me know what level of warming you want!
 here is one [arbitrary site-site 10](https://github.com/lizzieinvancouver/decsens/blob/master/analyses/figures/simsiteplots/decsensplot_warm__site_10_.pdf) there are other sites in the folder "simsiteplots"

**Comment by lizzieinvancouver** [comment]
@AileneKane Check our code to see if we can turn down any sigma that may strengthen the regression (increase beta or reduce sigma in linear regression) to make trends more obvious?
